### ISSUE TITLE
directive: facets

### ISSUE THREAD

**Issue by drjova** [inveniosoftware/invenio-search-js#20]
![screen shot 2015-12-11 at 17 38 45](https://cloud.githubusercontent.com/assets/4287772/11749503/73d04e9e-a02e-11e5-8452-f25d9058a685.png)

ping @tiborsimko @jirikuncar @lnielsen

**Comment by tiborsimko** [comment]
Looking at the screenshot, do you want to use `OR` rather than `AND` to combine different facets together?  The typical behaviour is: (1) `(value1 OR value2)` when selecting several values inside the same facet, and (2) `facet1:(value1 OR value2) AND facet2:value3` when combining several facets together.

**Comment by jirikuncar** [comment]
We should not build an Invenio query with selected facets as it's quite hard to manipulate such query later. Instead use one of following techniques:

(a) serialized state of facet component
(b) url arguments: `<facet_name>=[-]<value>`

**Comment by jirikuncar** [comment]
Closed via 7e900e50bff77771fc25388690b4300bc5bd8211.
